services:
 api:
  image: esg-solana-reporter-api:latest
  container_name: esg-solana-reporter-api
  restart: always
  volumes:
   - ./:/app
   - /app/node_modules
  ports:
   - 4000:4000
  command: npm run start:dev
  network_mode: host