services:
  postgres:
     image: postgres:latest
     container_name: postgres
     restart: always
     environment:
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=${POSTGRES_DB}
     ports:
       - '5432:5432'
     volumes:
       - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./DB_data:/var/lib/postgresql/data
     network_mode: host


  pgadmin:
     image: dpage/pgadmin4:latest
     container_name: pgadmin
     environment:
       - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
       - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
     depends_on:
       - postgres
     ports:
       - "5050:80"
     volumes:
       - ./data/pgadmin:/var/lib/pgadmin
     network_mode: host

