services:
  postgres:
     image: postgres:latest
     container_name: postgres
     restart: always
     environment:
       - POSTGRES_USER=${POSTGRES_USER:-postgres}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
       - POSTGRES_DB=${POSTGRES_PASSWORD:-electrodo}
     ports:
       - '5432:5432'
     network_mode: host


  pgadmin:
     image: dpage/pgadmin4:latest
     container_name: pgadmin
     environment:
       PGADMIN_DEFAULT_EMAIL: 1@mail.com
       PGADMIN_DEFAULT_PASSWORD: 12345678aA@
     depends_on:
       - postgres
     ports:
       - "5050:80"
     network_mode: host

